version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: scripts/stop-tomcat.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start-tomcat.sh
      timeout: 300
