version: 0.0
resources:
  - myJavaApp:
      type: EC2/Instance
      properties:
        content: /home/ubuntu
hooks:
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: codedeployuser
  BeforeInstall:
    - location: scripts/before-install.sh
  AfterInstall:
    - location: scripts/after-install.sh
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 300
      runas: codedeployuser
