version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Compiling the Java code..."
      - mvn clean compile  # Replace with your Maven compile command
  build:
    commands:
      - echo "Running tests..."
      - mvn test  # Replace with your Maven test command
