version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk17
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Compiling the Java code..."
      - ./mvn build  # Use your build command (e.g., gradle, maven)
  build:
    commands:
      - echo "Running tests..."
      - ./mvn test
